array_layout = "Block"
array_width = 80

comment_width = 100
condense_wildcard_suffixes = true

fn_call_width = 100

max_width = 100

reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true

use_try_shorthand = true
wrap_comments = true

write_mode = "Diff"
