[package]
name = "cocaine-http-proxy"
version = "0.1.0"
authors = ["Evgeny Safronov <division494@gmail.com>"]

[dependencies]
log = "0.3"
net2 = "0.2"
rand = "0.3"
futures = "0.1"
itertools = "0.5"
num_cpus = "1.0"

serde = "0.9"
serde_derive = "0.9"
serde_yaml = "0.6"

tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"

hyper = { git = "https://github.com/hyperium/hyper" }

cocaine = { path = "../cocaine-framework-rust" }
rmp-serde = "0.12.3"
rmpv = { version = "0.3.3", features = ["with-serde"] }

clap = "~2.20.5"

slog = "1.5"
slog-term = "1.5"

[profile.dev]
panic = "abort"

[profile.release]
debug = true
panic = "abort"
