# IP address for HTTP listeners to bind on.
addr: "::1"

# Port for HTTP listeners to bind on.
port: 8080

threads:
  http: 8
  network: 16

monitoring:
  addr: "::1"
  port: 10000

# Locator endpoints.
# These are passed directly into the cocaine-framework for service resolution.
# We also assume that all of these locator(s) are identical, i.e. connected to
# a single discovery component.
locators:
  - ["::", 10053]

# Logging settings. All logs are written directly into the logging service.
# Omit this section to disable logging into the Cocaine.
logging:
  # Service name into which all logging will be redirected.
  name: logging-proxy
  # Source prefix.
  # For example, access logs will have the source field `<prefix>/access`.
  prefix: proxy
  # Severity filter.
  # Logging events with severity less than specified will be dropped. Allowed
  # values are: [debug, info, warn, error].
  severity: debug

## Default pool size for applications.
#pool: 10
## Fine-grained application settings.
#app:
#  echo:
#    pool: 4
