# Network settings for the proxy.
network:
  # Tuple of an IP address with port for HTTP listener to bind on.
  # Note that binding on `::` will bind on `0.0.0.0` too as long as
  # the `net.ipv6.bindv6only` sysctl is set to 0 (default).
  addr: ["::", 8080]
  # Limit for the queue of incoming connections.
  backlog: 128

# Number of worker threads.
# The proxy uses main thread for accepting connections and `threads` threads
# for serving requests.
threads: 24

# Monitoring server settings.
# The monitoring server consumes one additional thread for serving requests.
monitoring:
  addr: ["::1", 10000]

# Locator endpoints.
# These are passed directly into the cocaine-framework for service resolution.
# We also assume that all of these locator(s) are identical, i.e. connected to
# a single discovery component.
locators:
  - ["::", 10053]

# Logging settings. All logs are written directly into the logging service.
# Omit this section to disable logging into the Cocaine.
logging:
  # The following fields can be configured:
  # - name: service name into which all logging will be redirected.
  # - source: source field for logging service.
  # - severity: severity filter.
  #   Logging events with severity less than specified will be dropped. Allowed
  #   values are: [debug, info, warn, error].
  common:
    name: logging
    source: proxy/common
    severity: info
  access:
    name: logging-access
    source: proxy/access
    severity: warn

## Default pool size for applications.
#pool: 10
## Fine-grained application settings.
#app:
#  echo:
#    pool: 4
